<?php
// ELMS: Requirement Dashboard OG
// Development Sponsored by The Pennsylvania State University
// ELMS is Copyright (C) 2008-2012  The Pennsylvania State University
//
// Bryan Ollendyke
// bto108@psu.edu
//
// Keith D. Bailey
// kdb163@psu.edu
//
// 12 Borland
// University Park,  PA 16802

/**
 * @file
 * Add requirement dashboards to og and implement common requirements
 */

/**
 * Implementation of hook_requirement_dashboard_provider().
 */
function requirement_dashboard_og_requirement_dashboard_provider() {
  $dashboards['og'] = array(
    'title' => t('Group stats'),
    'path' => 'node/%node/og_stats',
  );
  return $dashboards;
}

/**
 * Implementation of hook_dashboard_requirements().
 */
function requirement_dashboard_og_dashboard_requirements($provider) {
  switch ($provider) {
    case 'og':
      $group = og_get_group_context();
      $requirements['name'] = array(
        'title' => t('Group name'), 
        'value' => $group->title,
        'severity' => REQUIREMENT_INFO,
      );
      $requirements['description'] = array(
        'title' => t('Description'), 
        'value' => $group->og_description,
        'severity' => REQUIREMENT_INFO,
      );
      // if theme is set then list the theme used
      if (isset($group->og_theme)) {
        $requirements['theme'] = array(
          'title' => t('Theme'), 
          'value' => $group->og_theme,
          'severity' => REQUIREMENT_INFO,
        );
      }
    break;
  }
  return $requirements;
}

/**
 * Implementation of hook_menu_alter().
 */
function requirement_dashboard_og_menu_alter(&$items) {
  if (isset($items['node/%node/og_stats'])) {
    $items['node/%node/og_stats']['access callback'] = 'requirement_dashboard_og_status_access';
    $items['node/%node/og_stats']['access arguments'] = array(1);
  }
}

/**
 * Callback to only implement on group types
 */
function requirement_dashboard_og_status_access($node) {
  return og_is_group_type($node->type) ? user_access('view og requirements dashboard') : FALSE;
}