<?php

include_once('elms_id_best_practices.features.inc');

/**
 * Implementation of hook_menu().
 */
function elms_id_best_practices_menu() {
  $items = array();
  $items['syllabus'] = array(
    'title' => 'Syllabus',
    'page callback' => '_elms_id_best_practices_page_syllabus',
    'access callback' => '_elms_id_best_practices_access_feature',
    'access arguments' => array('syllabus'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
    'file' => 'elms_id_best_practices.pages.inc',
    'weight' => -2,
  );
  $items['elms_help'] = array(
    'title' => 'Help',
    'page callback' => '_elms_id_best_practices_page_help',
    'access callback' => '_elms_id_best_practices_access_feature',
    'access arguments' => array('elms_help'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
    'file' => 'elms_id_best_practices.pages.inc',
    'weight' => -1,
  );
  $items['features/elms_id_best_practices'] = array(
    'title' => 'Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_id_best_practices_settings'),
    'access callback' => '_elms_id_best_practices_access_check_admin',
    'access arguments' => module_exists('spaces') ? array() : array('administer site configuration'),
    'type' => MENU_CALLBACK,
    'file' => 'elms_id_best_practices.pages.inc',
  );
  $items['admin/elms/id_best_practices'] = array(
    'title' => 'ID best practices',
    'description' => 'Default settings related to instructional best practices',
    'page callback' => 'elms_id_best_practices_settings_overview',
    'access arguments' => array('administer elms configuration'),
    'file' => 'elms_id_best_practices.admin.inc',
  );
  $items['admin/elms/id_best_practices/settings'] = array(
    'title' => 'ID default settings',
    'description' => 'Default settings related to instructional best practices',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('elms_id_best_practices_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'elms_id_best_practices.pages.inc',
  );
  return $items;
}

/**
 * Implementation of hook_menu_alter().
 */
function elms_id_best_practices_menu_alter(&$items) {
  // add additional application path checker
  $items['applications']['access arguments'][0][0] = 'elms_id_best_practices_access_feature_perms';
}

/**
 * Access callback for spaces, with extra permission checking.
 */
function elms_id_best_practices_access_feature_perms($op = 'view', $feature, $account = NULL, $space = NULL, $perms = array()) {
  $access = spaces_access_feature($op, $feature, $account, $space);
  if (!empty($perms)) {
    foreach ($perms as $perm) {
      $access = $access && user_access($perm);
    }
  }
  $has_values = TRUE;
  if (count(variable_get('elms_id_bp_resources', array())) == 0) {
    $has_values = FALSE;
  }
  return ($access && $has_values);
}

/**
 * Callback for menu access based on values being set and feature active.
 */
function _elms_id_best_practices_access_feature($option) {
  // default is to display, these cases try to invalidate
  $display = TRUE;
  switch ($option) {
    case 'syllabus':
      // hide syllabus if type is invalid
      if (variable_get('elms_id_bp_syllabus_type', '') == '') {
        $display = FALSE;
      }
    break;
    case 'elms_help':
      // hide help if type is empty
      if (variable_get('elms_id_bp_help', '') == '') {
        $display = FALSE;
      }
    break;
  }
  return ($display && spaces_access_feature('view', 'elms_id_best_practices'));
}

// helper function for access verification
function _elms_id_best_practices_access_check() {
  // make sure the feature is activated
  if (spaces_access_feature('view', 'elms_id_best_practices')) {
    return user_access('manage features');
  }
  return 0;
}
// helper function for access verification
function _elms_id_best_practices_access_check_admin() {
  // make sure the feature is activated
  if (spaces_access_feature('view', 'elms_id_best_practices')) {
    return user_access('spaces_access_admin');
  }
  return 0;
}

/**
 * Implementation content generation from wysiwyg templates module.
 */
function _elms_id_best_practices_get_template($tid) {
  $body = '';
  // try and match the template to one in the database
  if (module_exists('wysiwyg_template')) {
    $body = db_result(db_query("SELECT body FROM {wysiwyg_templates} WHERE tid=%d", $tid));
  }
  return $body;
}

/**
 * Implementation of hook_book_outline_builder_template().
 */
function elms_id_best_practices_book_outline_builder_template() {
  $outline['unit_outline'] = array(
    'title' => 'Unit / topical outline',
      array(
        'type' => 'page',
        'title' => 'Introduction',
        'content' => _elms_id_best_practices_get_template(10),
        'format' => 2,
      ),
      array(
        'type' => 'page',
        'title' => 'Unit @i',
        'content' => _elms_id_best_practices_get_template(10),
        'format' => 2,
        'duplicate' => TRUE,
        'children' => array(
          array(
            'type' => 'page',
            'title' => 'Lesson @i',
            'content' => _elms_id_best_practices_get_template(rand(13, 15)),
            'format' => 2,
            'duplicate' => 3,
            'children' => array(
              array(
                'type' => 'page',
                'title' => 'Introduction',
                'content' => _elms_id_best_practices_get_template(rand(13, 15)),
                'format' => 2,
              ),
              array(
                'type' => 'page',
                'title' => 'Content page',
                'content' => _elms_id_best_practices_get_template(rand(13, 15)),
                'format' => 2,
              ),
              array(
                'type' => 'page',
                'title' => 'Summary',
               'content' => _elms_id_best_practices_get_template(rand(13, 15)),
               'format' => 2,
              ),
            ),
          ),
        ),
      ),
  );
  $outline['lesson_outline'] = array(
    'title' => 'Lesson outline',
      array(
        'type' => 'page',
        'title' => 'Lesson @i',
        'content' => _elms_id_best_practices_get_template(10),
        'format' => 2,
        'duplicate' => TRUE,
        'children' => array(
            array(
              'type' => 'page',
              'title' => 'Introduction',
              'content' => _elms_id_best_practices_get_template(rand(13, 15)),
              'format' => 2,
            ),
            array(
              'type' => 'page',
              'title' => 'Page 1',
              'content' => _elms_id_best_practices_get_template(rand(13, 15)),
              'format' => 2,
            ),
            array(
              'type' => 'page',
              'title' => 'Page 2',
              'content' => _elms_id_best_practices_get_template(rand(13, 15)),
              'format' => 2,
            ),
            array(
              'type' => 'page',
              'title' => 'Page 3',
              'content' => _elms_id_best_practices_get_template(rand(13, 15)),
              'format' => 2,
            ),
            array(
             'type' => 'page',
             'title' => 'Summary',
             'content' => _elms_id_best_practices_get_template(rand(13, 15)),
             'format' => 2,
            ),
          ),
      ),
  );
  return $outline;
}

/**
 * Implementation of hook_block().
 */
function elms_id_best_practices_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('Instructor contact'),
      'weight' => 0,
      'status' => 0,
    );
    return $blocks;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
          $block['title'] = t('Instructor contact');
          $block['content'] = _elms_id_best_practices_contact_info_block();
      break;
    }
    return $block;
  }
}

/**
 * Callback for instructor contact info block.
 */
function _elms_id_best_practices_contact_info_block() {
  $content = variable_get('elms_id_bp_instructor_block', '');
  if ($content != '') {
    return $content;
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function elms_id_best_practices_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
  case 'insert':
    // check for groups created
    if (og_is_group_type($node->type)) {
      module_load_include('inc', 'elms_id_best_practices', 'elms_id_best_practices.pages');
      // create help and syllabus pages on group node insert
      _elms_id_best_practices_make_single_page($node, 'Course syllabus');
      _elms_id_best_practices_make_single_page($node, 'Course help');
    }
  }
}

/**
 * Implementation of hook_html_export_add_path_provider().
 */
function elms_id_best_practices_html_export_add_path_provider() {
  $items = array(
    'elms_idbp' => array(
      'title' => 'ELMS: Best practices paths',
      'callback' => '_elms_id_best_practices_html_export_paths',
    ),
  );
  return $items;
}

/**
 * Callback for elms_idbp provider.
 */
function _elms_id_best_practices_html_export_paths() {
  // account for purl or addresses all bomb out
  $group = og_get_group_context();
  $base = '';
  if (isset($group->purl)) {
    $base = $group->purl .'/';
  }
  // provide paths that need to be loaded with this module enabled
  $paths = array(
    $base .'syllabus' => $base .'syllabus',
    $base .'help' => $base .'help',
    $base .'applications' => $base .'applications',
  );
  return $paths;
}